name: molecular_transformer
channels:
  - conda-forge
dependencies:
  - pip:
      - torchtext==0.3.1
      - pytorch==0.4
  - conda-forge::python=3.5
  - conda-forge::pip
  - conda-forge::rdkit
  - conda-forge::future
  - conda-forge::six
  - conda-forge::tqdm
  - conda-forge::pandas
  - torchvision
